"""Initial migration - create exercises, workouts, and join tables

Revision ID: 0398abf9b241
Revises: 
Create Date: 2026-07-14 21:59:40.864399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0398abf9b241'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('equipment_needed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercises')),
    sa.UniqueConstraint('name', name=op.f('uq_exercises_name'))
    )
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('duration_minutes > 0', name=op.f('ck_workouts_check_positive_duration')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workouts'))
    )
    op.create_table('workout_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_workout_exercises_exercise_id_exercises')),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name=op.f('fk_workout_exercises_workout_id_workouts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_exercises'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_exercises')
    op.drop_table('workouts')
    op.drop_table('exercises')
    # ### end Alembic commands ###
